dist: xenial

env:
  global:
    - TWINE_USERNAME="anthrotype"
    - secure: wg1vkiWvySib0Zz37R4GZyHEcW84774P09NuT8B7EyAH2McGSmCw8SrbwqzLx8VIayr7hw5ttTSrU2mSf1oapZzhRvetAW3FvaUqlBLfDIXUFbbsMXUgEPIiaahaxmjhAKHkLcZEKJyyzHwAXzCVF1KTE7z4UmjEy0whl4Tf4MP+0OSbTKcTqxNYIWj/IWn22lt8zjtoUdWFR/qmzX/WPtgOLT49CkXKOPLdndohDOjQqiALq07ofiyeL+zBYqIT/OYsX1w+bkaI1Rbj4ovr0MRPprs6Vf/s9qcyarVQgUmeSCwQDarDx5nC+hLnSY+6k8Tk4xQC94QE0LmKvCcNMQFZ/qcP5YJ4oKZJ0nIjEwktpRGLQzrHrTKqNHGMiBtRvwn1t/P8Wpl+KfbB6BjvkjzSGsLrWmzhX247zppy4u+wC4eozItgrTyHvo5Zv1BSYGlC9P9ql/pmFCt0N1Wnfal0trLTQAWS03Tt0m7Tv94Ss7LWlRqJWsOUsK2Jrygyr53ParRX4E96ho8vMGM1OWqrpaFEnYGRt5gp2SHrwBVUdJCUybw5RKH+npAG/8B0gvewGy9nSoo8+T/BYPKM41105Ses7O3ucKcgFy9NWunJYHPwQZLy5YPF9UdcKKa3Vdgm0oB8C6Qew2wYNftJXBmsJI2QtNTJBNHzY1xlNeo=

# The following prevents Travis from running CI on pull requests that come from a
# branch in the same repository. Without this, it will run the same CI for the
# pull request branch _and_ the pull request itself, which makes no sense.
branches:
  only:
    - master
    # We want to build wip/* branches since these are not usually used for PRs
    - /^wip\/.*$/
    # We want to build version tags as well.
    - /^v\d+\.\d+.*$/

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit

language: python

matrix:
  include:
    - python: 3.7
      env: TOXENV=lint
    - python: 3.6
      env: TOXENV=py36-cov
    - python: 3.7
      env: TOXENV=py37-cov

install:
  - pip install tox

script:
  - tox

after_success:
  - |
    if [ -n "$TRAVIS_TAG" ] && [ "$TRAVIS_REPO_SLUG" == "googlefonts/fontmake" ] && [ "$TOXENV" == "py37-cov" ]; then
      pip install --upgrade pip
      pip install --upgrade twine setuptools wheel shiv
      python setup.py sdist
      pip wheel --no-deps --wheel-dir dist .
      ./build_pyz.sh
      twine upload dist/*.whl dist/*.zip
    fi

deploy:
  # also create a Github Release with the current tag
  - provider: releases
    api_key:
      secure: ZZeHx2+Yc4gjEPVyhqySp700cF6Ro8xy0IOF0wD+BKOVi9/rj7AWfz5OBCb/3D18lji6lepXtEQ6/7AgqDLZNUk7R459g7GoczRt/M/iR3aXJslCiBTG/4r1O4ZCNXKLVgoX0Cavi1we7qKTot0wIYWcjk1TU9EmRoYpsnZTTWHKW0F2ZDd4O0IdWSUO6wF+g2DY4OxVy9zC7D2wdg53+LSRFao3w3hALZ7Rb32Icq/QdG+z4t9Vsa61keHULDH5MMMcUHQ6PbM96hBTydeTJrpwrojfX7WhE+SlptwH4cnTZPSFBqgOvrOwu9vKKI5TvUvfE4qt9QP+nZEfjrwnxBXMvYpRIDDoM+stc+NZ25xiEel3JXrmmue/VKtwbO4WaKSZWJXntyEcDFTnk32w6PmoawG1Rp1noVwL0b9sPXAYm4mw0yY4g+UoUsxRcxWFeKU1gXYIBGIKgqglys+WgnIUraqQcUuHn2l90n1DM86D2yOHsrg/NSFK1ePJAlNcz8rkYtUeCaffG2iyAjxf5IiqDx6k1flKphkLTqbc0eFkocj3ay7vnFINflcQRD4ISCEd5J2FuncnPkyUHTDPDYwjsNVuqceTF22e48NL+qfqLohbQ5aU6xiol6Pv4QQFOK+LG0bJb87DXlzJV9ZRjV0zai3wjhHuw2jfvvA4gHo=
    file_glob: true
    file: "shivs/*.zip"
    skip_cleanup: true
    on:
      repo: googlefonts/fontmake
      tags: true
      all_branches: true
      python: 3.7
